# Generated by Django 4.0.6 on 2022-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
